backend:
  name: github
  repo: constructions-incongrues/tumultes-template
  branch: main
  site_domain: https://decap-proxy.constructions-incongrues.net
  base_url: https://decap-proxy.constructions-incongrues.net
  auth_endpoint: /api/auth

site_url: https://constructions-incongrues.github.io/tumultes-template/

publish_mode: editorial_workflow
media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'tumultes' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Tumultes' # Used in the UI
    label_singular: 'Tumulte' # Used in the UI, ie: "New Post"
    icon: genres
    description: >
      Du son pour les oreilles
    folder: 'content/tumultes'
    slug: '{{slug}}'
    path: '{{slug}}/manifest'
    summary: '{{title}} par {{curatos}}'
    create: true # Allow users to create new documents in this collection
    editor:
      visualEditing: true
    format: json
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    media_folder: ''
    public_folder: ''
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: "Curators"
        name: "curators"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      -  label: 'Publish Date'
         name: 'date'
         widget: 'datetime'
         format: 'YYYY-MM-DD HH:mm'
         default: '{{now}}'     
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - { label: 'About', name: 'about', widget: 'markdown', hint: 'A few words...', required: false }
      - label: Tracks
        name: tracks
        widget: list
        required: false
        fields:
          - {label: Artist, name: artist, widget: string}
          - {label: Title, name: title, widget: string}
          - label: File
            name: file
            widget: file
            media_library: 
              allow_multiple: false
