backend:
  name: github
  repo: constructions-incongrues/tumultes
  branch: main
  site_domain: https://decap-proxy.constructions-incongrues.net
  base_url: https://decap-proxy.constructions-incongrues.net
  auth_endpoint: /api/auth
  auth_scope: repo # this is needed to fork the private repo
  open_authoring: true
  automatic_deployments: true

site_url: https://tumultes.incongru.org

publish_mode: editorial_workflow
media_folder: assets/uploads

show_preview_links: false
display_url: https://tumultes.incongru.org

editor:
    preview: false

collections: 
  - name: 'tumultes' 
    label: 'Tumultes'
    label_singular: 'Tumulte'
    icon: genres
    description: >
      Du son pour les oreilles
    folder: 'content/tumultes'
    slug: '{{slug}}'
    path: '{{slug}}/manifest'
    summary: '{{title}} [{{curators}}]'
    create: true # Allow users to create new documents in this collection
    editor:
      visualEditing: true
    format: json
    media_folder: ''
    public_folder: ''
    sortable_fields:
      fields: [title, publish_date]
      default:
        field: publish_date
        direction: descending # default: ascending
    view_groups:
      - label: Year
        field: publish_date
        pattern: \d{4}
      - label: Unlisted
        field: unlisted
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Unlisted', name: 'unlisted', widget: 'boolean', default: true }
      - label: "Curators"
        name: "curators"
        widget: "list"
        label_singular: Curator
        field:
          - { label: Name, name: name, widget: string }
      -  label: 'Publish Date'
         name: 'publish_date'
         widget: 'datetime'
         format: 'YYYY-MM-DD HH:mm'
         default: '{{now}}'     
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - { label: 'About', name: 'about', widget: 'markdown', required: false }
      - label: Tracks
        name: tracks
        widget: list
        required: false
        collapsed: true
        label_singular: Track
        summary: '{{artist}} - {{title}}'
        fields:
          - {label: Artist, name: artist, widget: string}
          - {label: Title, name: title, widget: string}
          - label: File
            name: file
            widget: file
            media_library: 
              allow_multiple: false
      - label: Configuration
        name: configuration
        widget: object
        fields:
          - label: Releases Downloads
            name: releases_downloads
            widget: select
            options: [flac, mp3, opus, ogg, wav]
            default: flac
            multiple: true
          - label: M3U
            name: m3u
            widget: select
            options: [enabled, disabled]
            default: disabled
          - label: Synopsis
            name: synopsis
            widget: markdown
          - label: More
            name: more
            widget: markdown
          - label: More (Label)
            name: synopsis
            widget: markdown            
          - { label: 'Copy Link', name: 'copy_link', widget: 'select', options: [enabled, disabled], required: false, default: enabled }
          - { label: 'Download Codes', name: 'download_codes', widget: 'list', required: false, field: {label: Code, name: code, widget: string} }
          

  - label: Settings
    name: settings
    icon: settings
    media_folder: '/content/images'
    public_folder: './images'
    files:
      - label: "Catalog"
        name: "catalog"
        file: "content/catalog.json"
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#title' }
          - { label: 'Synopsis', name: 'synopsis', widget: 'text', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#synopsis' }
          - { label: 'More', name: 'more', widget: 'markdown', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#more' }
          - { label: 'More (Label)', name: 'more_label', widget: 'markdown', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#more_label' }
          - { label: 'Base URL', name: 'base_url', widget: 'string', required: true, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#base_url' }
          - { label: 'Language', name: 'language', widget: 'string', required: true, default: 'fr', hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#language' }
          - { label: 'Cache Optimization', name: 'cache_optimization', widget: 'select', required: true, options: [delayed, immediate, wipe, manual], default: 'delayed', hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#cache_optimization' }
          - { label: 'Copy Link', name: 'copy_link', widget: 'select', options: [enabled, disabled], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#copy_link', default: enabled }
          - { label: 'Embedding', name: 'embedding', widget: 'select', options: [enabled, disabled], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#embedding', default: enabled }
          - { label: 'M3U', name: 'm3u', widget: 'select', options: [enabled, catalog, releases, disabled], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#m3u', default: enabled }
          - { label: 'Opengraph', name: 'opengraph', widget: 'select', options: [enabled, disabled], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#opengraph', default: enabled }
          - { label: 'Speed Controls', name: 'speed_controls', widget: 'select', options: [enabled, disabled], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#speed_controls', default: enabled }
          - { label: 'Faircamp Signature', name: 'faircamp_signature', widget: 'select', options: [enabled, disabled], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#faircamp_signature', default: enabled }
          - { label: 'Feeds', name: 'feeds', widget: 'select', options: [disabled, all, podcast_rss, atom, generic_rss], required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#feeds', default: atom }
          - { label: 'Label Mode', name: 'label_mode', widget: 'boolean', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#label_mode', default: false }
          - { label: 'Show Support Artists', name: 'show_support_artists', widget: 'boolean', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#show_support_artists', default: false }
          - { label: 'Feature Support Artists', name: 'feature_support_artists', widget: 'boolean', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#feature_support_artists', default: false }
          - label: 'Theme'
            name: 'theme'
            widget: 'object'
            required: false
            collapsed: true
            hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#theme'
            fields: 
              - name: base
                label: Base
                widget: select
                options: [light, dark]
                default: 'light'
              - name: background_image
                label: Background Image
                widget: image
                choose_url: false
              - name: accent_brightening
                label: Accent Brightening
                widget: number
                default: 0
              - name: accent_chroma
                label: Accent Chroma
                widget: number
                default: 0
              - name: accent_hue
                label: Accent Hue
                widget: number
                default: 0
              - name: background_alpha
                label: Background Alpha
                widget: number
                default: 0
              - name: base_chroma 
                label: Base Chroma
                widget: number
                default: 0
              - name: base_hue
                label: Base Hue
                widget: number
                default: 0
              - name: dynamic_range 
                label: Dynamic Range
                widget: number
                default: 0

          - { label: 'Home Image', name: 'home_image', widget: 'object', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#home_image', default: false, fields: [{name: description, label: Description, widget: string }, {name: file, label: File, widget: image, choose_url: false}] }
          - { label: 'Favicon', name: 'favicon', widget: 'image', required: false, hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#favicon' }
          - label: 'Links'
            name: 'links'
            widget: list
            collapsed: true
            label_singular: Link
            summary: '{{label}}'
            root: true
            required: false
            hint: 'https://simonrepp.com/faircamp/manual/catalog-catalog-eno.html#link'
            fields: 
              - label: Link
                name: link
                widget: object
                required: false
                fields:
                - label: Label
                  name: label
                  widget: string
                - label: URL
                  name: url
                  widget: string

          
          